@startuml

object participant
    participant : **//(PK)// participantId** = //unsigned int//
    participant : name = //varchar(256)//
object currency
    currency : **//(PK)// currencyId** = //unsigned int//
object contactType
    contactType : **//(PK)// contactTypeId** = //unsigned int//
object ledgerAccountType
    ledgerAccountType : **//(PK)// ledgerAccountTypeId** = //unsigned int//
object participantCurrency
    participantCurrency : **//(PK)// participantCurrencyId** = //unsigned int//
    participantCurrency : **//(FK)// currencyId** = //unsigned int//
    participantCurrency : **//(FK)// participantId** = //unsigned int//
    participantCurrency : **//(FK)// ledgerAccountTypeId** = //unsigned int//
object participantContact
    participantContact : **//(PK)// participantContactId** = //unsigned int//
    participantContact : **//(FK)// participantId** = //unsigned int//
    participantContact : **//(FK)// contactTypeId** = //unsigned int//
currency <|-- participantCurrency : //currencyId//
ledgerAccountType <|-- participantCurrency : //ledgerAccountTypeId//
participant <|-- participantCurrency : //participantId//
participant <|-- participantContact : //participantId//
contactType <|-- participantContact : //contactTypeId//

@enduml
