@startuml

participant "Mojaloop Adapter" as dfsp #B0D5FF
note over dfsp
    Participant
    DFSP interactions
end note

box Central-Settlement #FFFFF9
    participant "**API**" as cs_api
    participant "__api__ / Handler" as cs_handler
    participant "Application Layer\n(domain / service / facade)" as cs_domain

note over cs_api
        NodeJS interface
        invokes REST API
    end note

    note over cs_handler
        JSON request decoded &
        processed via handler
    end note

    note over cs_domain
        Expose service functions &
        handle database interactions
    end note

end box

box Storage #F9FFF9
	participant "TigerBeetle Client" as tb_client #D5E8D4
	collections "TigerBeetle Cluster" as tb_nodes #D5E8D4
	database "MySQL" as cl_db #DAE8FC
end box

autonumber
group Initiate Settlement
    dfsp -> cs_api : //JSON// \n**(settlement data)**
    cs_api -> cs_handler : Invoke handler
    cs_handler -> cs_domain : Invoke application layer
    cs_domain -> cl_db : Insert settlement data \n(excluding accounts)
    cs_domain <--> tb_client : Retrieve settlement \nwindow transactions
    cs_domain -> tb_client : Invoke settlement \naccount creation
    tb_client <--> tb_nodes : Create settlement accounts
    tb_client --> cs_domain : Return result
    cs_domain --> cs_handler : Return result
    cs_handler --> cs_api : Return result
    cs_api --> dfsp : Return //**settlement**// \nresult
end

@enduml
