@startuml

participant "Mojaloop Adapter" as dfsp #B0D5FF
note over dfsp
    Participant
    DFSP interactions
end note

box Central-Ledger #FFFFF9
    participant "Kafka\nConsumer" as cl_consume_kafka
        participant "__api__ / Handler" as cl_handler
        participant "Application Layer\n(domain / service / facade)" as cl_domain

        note over cl_consume_kafka
            Consume JSON
            requests from Kafka topic
        end note
    
        note over cl_handler
            JSON request decoded &
            processed via handler
        end note
    
        note over cl_domain
            Expose service functions &
            handle database interactions
        end note
end box

box Storage #F9FFF9
	Participant "TigerBeetle Client" as tb_client #D5E8D4
	collections "TigerBeetle Cluster" as tb_nodes #D5E8D4
	database "MySQL" as cl_db #DAE8FC
	database "Redis" as redis_cache #E1D5E7
end box

autonumber
group Create Participant
    dfsp -> cl_consume_kafka : //JSON// \n**(participant data)**
    cl_consume_kafka -> cl_handler : Invoke handler
    cl_handler -> cl_domain : Invoke service
    cl_domain <--> cl_db : Create Participant & return \nresult (this excludes the //account//)
    cl_domain -> tb_client : Create Participant //account//
    tb_client <--> tb_nodes : Create //account// \n& return result
    tb_client --> cl_domain : Return //account// create result
    cl_domain --> cl_handler : Return result
    cl_handler --> cl_consume_kafka : Return result
    cl_consume_kafka --> dfsp : Return result
end

@enduml
