@startuml

box Central-Settlement #FFFFF9
    participant "Application Layer\n(domain / service / facade)" as cs_domain

    note over cs_domain
        Expose service functions &
        handle database interactions
    end note
end box

box Storage #F9FFF9
	participant "TigerBeetle Client" as tb_client #D5E8D4
	collections "TigerBeetle Cluster" as tb_nodes #D5E8D4
	database "MySQL" as cs_db #DAE8FC
end box

autonumber
'group Settlement Event - //""PS_TRANSFERS_RESERVED"" -> ""PS_TRANSFERS_COMMITTED""// (putById)
group Settlement Event - Commit
    'cs_domain -> cs_domain : Current state is **""PS_TRANSFERS_RESERVED""**, invoke ""settlementTransfersCommit"".
    'cs_domain -> cs_db : Lookup base settlement data.
    cs_domain <-- tb_client : Retrieve //Transfers// with \n""PS_TRANSFERS_RESERVED"" state
    'cs_domain -> tb_client : Retrieve list of pending ""RESERVED""\n*//**tbLookupReserved**// - Based on ""settlementId"".
    'cs_domain --> cs_db : Perform the following inserts/updates against the database:\n*--//transferFulfilmentDuplicateCheck//-- Built in TB.\n*--//transferFulfilment//-- Built in TB.\n*--//transferStateChange//-- Built in TB.\n*--//participantPosition//-- Built in TB.
    'cs_domain -> tb_client : Lookup accounts associated with settlement via CS-TB interface:\n*//**tbLookupAccountsForSettlement**// - Based on ""settlementId"".
    cs_domain <-- tb_client : Retrieve the settlement accounts
    cs_domain -> tb_client : Commit reserved 2-phase //Transfers//:\n- ""SETTLEMENT""\n- ""HUB_RECONCILIATION""
    cs_domain -> cs_db : Update settlement state to \n""PS_TRANSFERS_COMMITTED""
    'cs_domain -> cs_domain : Determine state and counters for settlement accounts.
    'cs_domain -> cs_domain : Continue the settlement process.
end

@enduml
